typography_spectrum: 0.2510644136928022
color:
  brandColors:
    - '#ffffff'
    - '#009e5a'
    - '#e7bb5c'
    - '#4c8667'
    - '#5bbca6'
  brandStrength: 0
  lightness: 0.46734747011214495
  saturation: 0.014469481306150556
  rhythmicContrast: 0.4553361830767244
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7874125812668353
analytics:
  google: null
  facebook: null
  twitter: null
name: CommunityInsurance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Community Insurance Online
    url: 'http://www.greatci.com'
    type: external
favicon: null
title: TheStache
purpose: []
