name: CommunityInsurance
favicon: null
layout_spectrum: 0.7874125812668353
typography_spectrum: 0.2510644136928022
title: TheStache
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009e5a'
    - '#e7bb5c'
    - '#4c8667'
    - '#5bbca6'
  brandStrength: 0
  lightness: 0.46734747011214495
  saturation: 0.014469481306150556
  rhythmicContrast: 0.4553361830767244
purpose: []
